base: flora_gemma3_1b_it.yaml

training:
  output_dir: ./outputs/entropy_gating_gemma3_1b_it

gating:
  method: entropy_gating
  entropy_window: 4

logging:
  wandb_run_name: entropy_gating_gemma3_1b_it
