base: baseline.yaml

training:
  output_dir: ./outputs/flora_gemma3_1b_it

gating:
  method: flora
  topk_tokens: 0.2
  sketch_dim: 512
  topk_logits: 128

logging:
  wandb_run_name: flora_gemma3_1b_it
