base: baseline.yaml

training:
  output_dir: ./outputs/flora_gemma3_1b_pt

gating:
  method: flora
  topk_tokens: 0.2
  sketch_dim: 512
  topk_logits: 128
  weight_clip: 10.0

logging:
  wandb_run_name: flora_gemma3_1b_pt
