base: baseline.yaml

training:
  output_dir: ./outputs/quick_gemma3_1b_it

gating:
  method: slora
  topk_tokens: 0.2
  sketch_dim: 1024
  topk_gradients: 128

logging:
  wandb_run_name: quick_gemma3_1b_it
