# Quick test config: Gemma-3-1B-it with SLoRA enabled
base: baseline.yaml

training:
  output_dir: ./outputs/quick_gemma3_1b_it

slora:
  enable: true
  m: 1024
  k: 32
  target_accept_rate: 0.40
  initial_threshold: 0.05
  controller_lr: 0.01
  burn_in: 100
  seed: 0
  reorth_every: 32
  k_topk: 128
  random: false
  subspace_decay: 0.99

logging:
  wandb_run_name: quick_gemma3_1b_it
